version: '3.4'

services:
  normativecalculator.api:
    image: ${DOCKER_REGISTRY-}normativecalculatorapi
    build:
      context: .
      dockerfile: NormativeCalculator.Api/Dockerfile

  db:
    container_name: sql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 8082:1433

  # angular-ui:
  #   build:
  #     context: .
  #     dockerfile: NormativeCalculatorApp/Dockerfile
  #   ports:
  #     - "4201:4201"
  #   container_name: angular-ui
  #   volumes:
  #     - ./app-ui:/usr/src/app/app-ui
  #     - /usr/src/app/app-ui/node_modules


    